BlocXChange/Models/ErrorViewModel.cs
using System;

namespace BlocXChange.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlocXChange/Models/Exchange.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BlocXChange.Models
{
    public class Exchange
    {
        [Key]
        public int DataNo { get; set; }

        /// <summary>
        /// 거래가 생성되었을 때, 판매자의 고유번호
        /// </summary>
        [Required]
        public int Seller { get; set; }

        /// <summary>
        /// 거래가 생성되었을 때, 구매자의 고유번호
        /// </summary>
        [Required]
        public int Buyer { get; set; }

        /// <summary>
        /// 거래가 생성되었을 때, 거래 금액
        /// </summary>
        [Required]
        public int Value { get; set; }

        [Required]
        public int GameNo { get; set; }

        [ForeignKey("GameNo")]
        public virtual Game Game { get; set; }
    }
}

BlocXChange/Models/Fluctuation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BlocXChange.Models
{
    public class Fluctuation
    {
        [Key]
        public int DataNo { get; set; }

        /// <summary>
        /// 주가를 변동시켜야 할 시간의 Ticks값
        /// </summary>
        [Required]
        public long FlucTimeTicks { get; set; }

        /// <summary>
        /// 주가 변동이 일어날 회사
        /// </summary>
        [Required]
        public int CompanyNo { get; set; }

        /// <summary>
        /// 주가 변동폭
        /// </summary>
        [Required]
        public int FlucValue { get; set; }

        [Required]
        public int GameNo { get; set; }

        [ForeignKey("GameNo")]
        public virtual Game Game { get; set; }
    }
}

BlocXChange/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlocXChange.Models
{
    public class Game
    {
        [Key]
        public int GameNo { get; set; }
        
        [Required]
        public string GameID { get; set; }

        [Required]
        public string GamePassword { get; set; }

        /// <summary>
        /// 게임을 생성할 때 자동으로 생성되는 고유 코드
        /// 게임에 참가할 때 입력 필요
        /// </summary>
        [Required]
        public string GameKey { get; set; }

        /// <summary>
        /// 게임이 시작된 시간
        /// </summary>
        [Required]
        public DateTime InitialTime { get; set; }
        
        /// <summary>
        /// 게임이 중간에 일시정지된 경우, 일시중지된 시간을 기록
        /// </summary>
        [Required]
        public long SuspendedTicks { get; set; }
    }
}

BlocXChange/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BlocXChange.Models
{
    public class Stock
    {
        [Key]
        public int DataNo { get; set; }

        /// <summary>
        /// 게임 내에서 등장하는 회사의 고유 번호
        /// </summary>
        [Required]
        public int CompanyNo { get; set; }

        /// <summary>
        /// 고유 번호가 가르키는 회사의 주가
        /// </summary>
        [Required]
        public int StockValue { get; set; }

        [Required]
        public int GameNo { get; set; }

        [ForeignKey("GameNo")]
        public virtual Game Game { get; set; }
    }
}

BlocXChange/ViewModels/NewGameViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlocXChange.ViewModels
{
    public class NewGameViewModel
    {
        [Required(ErrorMessage = "사용자 ID를 입력하세요")]
        public string GameID { get; set; }

        [Required(ErrorMessage = "사용자 비밀번호를 입력하세요")]
        public string GamePassword { get; set; }
    }
}

BlocXChange/Controllers/GamerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BlocXChange.Controllers
{
    public class GamerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BlocXChange/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BlocXChange.Models;

namespace BlocXChange.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlocXChange/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlocXChange.DataContext;
using Microsoft.AspNetCore.Mvc;
using BlocXChange.ViewModels;
using BlocXChange.Models;
using BlocXChange.Class;
using Microsoft.AspNetCore.Http;

namespace BlocXChange.Controllers
{
    public class MasterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewGame()
        {
            RandomKey.GetRandomKey(6);
            return View();
        }

        [HttpPost]
        public IActionResult NewGame(NewGameViewModel model)
        {
            if(ModelState.IsValid)
            {
                using (var db = new BlocXChangeDBContext())
                {
                    if(db.Games.FirstOrDefault(u => u.GameID == model.GameID) != null) // ID 중복 확인
                    {
                        ModelState.AddModelError("", "다른 ID를 사용해주세요");
                        return View(model);
                    }

                    // ID 미 중복시
                    string newGameKey = RandomKey.GetRandomKey(6);

                    while(db.Games.FirstOrDefault(u => u.GameKey == newGameKey) != null)
                    {
                        newGameKey = RandomKey.GetRandomKey(6);
                    }

                    Game newGame = new Game
                    {
                        GameID = model.GameID,
                        GamePassword = model.GamePassword,
                        GameKey = newGameKey,
                        InitialTime = DateTime.Now,
                        SuspendedTicks = 0
                    };
                    db.Games.Add(newGame);

                    var GenData = new GenerateGameData(newGame);
                    foreach(var i in GenData.GetStocks()) // 주가 데이터 생성
                    {
                        db.Stocks.Add(i);
                    }
                    foreach(var i in GenData.GetFluctuations()) // 주가 변동 데이터 생성
                    {
                        db.Fluctuations.Add(i);
                    }
                    
                    db.SaveChanges();

                    HttpContext.Session.SetString("GAME_MASTER_KEY", newGameKey);
                    return Redirect("Play/?GameKey=" + newGameKey);
                    
                }
            }
            return View(model);
        }

        public IActionResult EnterGame()
        {
            return Redirect("Index");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="GameKey"></param>
        /// <returns></returns>
        public IActionResult Play(string GameKey)
        {
            if(HttpContext.Session.GetString("GAME_MASTER_KEY") != GameKey)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

BlocXChange/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

BlocXChange/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BlocXChange/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

BlocXChange/Views/Master/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<div>
    <ul>
        <li><a class="btn btn-primary" asp-controller="Master" asp-action="NewGame">새 게임 생성</a></li>
        <li><a class="btn btn-default" asp-controller="Master" asp-action="EnterGame">생성된 게임 접속</a></li>
    </ul>

</div>

BlocXChange/Views/Master/NewGame.cshtml
@{
    ViewData["Title"] = "NewGame";
}
@model BlocXChange.ViewModels.NewGameViewModel

<h2>새 게임 생성</h2>

<div class="body-content">
    <form class="form-horizontal" method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            <label>게임 ID</label>
            <input type="text" class="form-control" asp-for="GameID" placeholder="게임 ID 입력" />
            <span class="text-danger" asp-validation-for="GameID"></span>
        </div>

        <div class="form-group">
            <label>게임 비밀번호</label>
            <input type="password" class="form-control" asp-for="GamePassword" placeholder="게임 비밀번호 입력" />
            <span class="text-danger" asp-validation-for="GamePassword"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">생성</button>
            <a class="btn btn-warning" href="#">취소</a>
        </div>
    </form>

</div>

BlocXChange/Views/Master/Play.cshtml
@{
    ViewData["Title"] = "Play";
}
@section head{ 
    <link href="~/css/MasterPlayView.css" rel="stylesheet" />
}
<div class="col-lg-5 card">
    <div class="group">
        <div class="box box-turn-display">
            <label>1턴째</label>
        </div>
        <div>
            <div class="btn btn-next-turn">다음 턴</div>
            <div class="btn btn-next-turn">이전 턴</div>
        </div>
    </div>
</div>

<div class="col-lg-7">
    <table>
        <thead>

        </thead>
        <tr></tr>
        <tr>
            <td>aa</td>
            <td>bb</td>
        </tr>
    </table>
</div>

BlocXChange/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlocXChange</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,700&amp;subset=korean" rel="stylesheet">
    @RenderSection("head", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BlocXChange</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetInt32("ID") != null)
                    {
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Master" asp-action="Index">게임 주최하기</a></li>
                        <li><a asp-area="" asp-controller="Gamer" asp-action="Index">게이머로 참가하기</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    
    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>